  - name: creare utente cb0 sulla VM
    vars:
     mypassword: "Birex2023"
    ansible.builtin.user:
     name: "cb0"
     state: present
     password: "{{ mypassword | password_hash('sha512') }}"
     shell: /bin/bash
     group: sudo
     comment: ExT_User
